name: Deploy Dockerized Portfolio to EC2

on:
  push:
    branches:
      - main  # Trigger deployment on push to the main branch

jobs:
  deploy:
    runs-on: self-hosted  # Specify that this job runs on a self-hosted runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        run: |
          docker --version

    

      - name: Build Docker Image
        run: |
          docker build -t my-portfolio .  # Build the Docker image using default Docker build command

      - name: Stop and Remove Existing Docker Container
        run: |
          CONTAINER_ID=$(docker ps -q --filter "name=my-portfolio")
          if [ -n "$CONTAINER_ID" ]; then
            docker stop $CONTAINER_ID
            docker rm $CONTAINER_ID
          fi

      - name: Run Docker Container
        run: |
          docker run -d --name my-portfolio -p 80:80 my-portfolio
