name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # or the branch you want to trigger the workflow

jobs:
  build-and-deploy:
    runs-on: self-hosted  # Use the self-hosted runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Optional: Cache Docker layers if needed
      # - name: Cache Docker layers
      #   uses: docker/cache-action@v2
      #   with:
      #     path: /tmp/.buildx-cache

      - name: Build Docker image
        run: |
          docker build -t my-portfolio-image .

            docker run -d --name portfolio-container -p 80:80 my-portfolio-image
          EOF
