name: Deploy Dockerized Portfolio to EC2

on:
  push:
    branches:
      - main  # Trigger deployment on push to the main branch

jobs:
  deploy:
    runs-on: self-hosted  # Specify that this job runs on a self-hosted runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Stop GitHub Actions Runner Service
        run: |
          sudo ./svc.sh stop
        working-directory: /home/ubuntu/actions-runner

      - name: Start GitHub Actions Runner Service
        run: |
          sudo ./svc.sh start
        working-directory: /home/ubuntu/actions-runner

      - name: Set up Docker Buildx
        run: |
          docker buildx create --use

      - name: Build Docker Image
        run: |
          docker buildx build -t my-portfolio:latest .

      - name: Stop existing Docker container
        run: |
          CONTAINER_ID=$(docker ps -q --filter "name=my-portfolio")
          if [ -n "$CONTAINER_ID" ]; then
            docker stop $CONTAINER_ID && docker rm $CONTAINER_ID
          fi

      - name: Run Docker Container
        run: |
          docker run -d --name my-portfolio -p 80:80 my-portfolio:latest
