name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Fix Permissions
      run: sudo chown -R ubuntu:ubuntu /var/www/html/Portfolio

    - name: Pull Latest Code
      run: |
        sudo su -
        cd /var/www/html/Portfolio
        git pull

    - name: Deploy
      run: |
        cd /var/www/html/Portfolio
        git pull

