name: Deploy Static Portfolio

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build -t portfolio .

    - name: Deploy locally or to a service
      run: |
        docker run -d -p 8080:80 portfolio
        # Alternatively, deploy to a service like AWS S3 or GitHub Pages

